### ISSUE TITLE
Feature: Invoice Page

### ISSUE THREAD

**Issue by mateuszdomagala** [mateuszdomagala/vue-invoice-app#17]
# Epic Title

Feature: Invoice Page

## Epic Description

This feature will add an invoice page view where the user can read all the details of the invoice.

## List of Tasks 

1. [x] [Task: Initial Layout of the Invoice Page](https://github.com/mateuszdomagala/vue-invoice-app/issues/26)
2. [x] [Task: Editing an invoice](https://github.com/mateuszdomagala/vue-invoice-app/issues/15)
3. [x] [Task: Deleting an invoice](https://github.com/mateuszdomagala/vue-invoice-app/issues/16)
4. [x] [Task: Mark the invoice as paid](https://github.com/mateuszdomagala/vue-invoice-app/issues/18)
5. [x] [Task: Route transitions](https://github.com/mateuszdomagala/vue-invoice-app/issues/31)
6. [x] [Task: Firestore rules and checking ownership](https://github.com/mateuszdomagala/vue-invoice-app/issues/33)
