### ISSUE TITLE
Feature: Signup/Login page

### ISSUE THREAD

**Issue by mateuszdomagala** [mateuszdomagala/vue-invoice-app#2]
# Epic Title

Feature: Signup/Login page

## Epic Description

This feature will add a signup/login page where the user can create an account and login to the site.

## List of Tasks

1. [x] [Task: Add Firebase to the project](https://github.com/mateuszdomagala/vue-invoice-app/issues/3)
2. [x] [Task: Signup view](https://github.com/mateuszdomagala/vue-invoice-app/issues/4)
3. [x] [Task: Login view](https://github.com/mateuszdomagala/vue-invoice-app/issues/5)
4. [x] [Task: Route transitions](https://github.com/mateuszdomagala/vue-invoice-app/issues/31)
