### ISSUE TITLE
Feature: Home Page

### ISSUE THREAD

**Issue by mateuszdomagala** [mateuszdomagala/vue-invoice-app#7]
# Epic Title

Feature: Home Page

## Epic Description

This feature will add a home page where the user can view a list of invoices, create new ones, and filter them by status.

![image](https://res.cloudinary.com/dz209s6jk/image/upload/v1614355720/Challenges/v760dr4mqyro0xey3dr3.jpg)

## List of Tasks 

1. [x] [Task: Sign out users](https://github.com/mateuszdomagala/vue-invoice-app/issues/10)
2. [x] [Task: Toggle light and dark mode](https://github.com/mateuszdomagala/vue-invoice-app/issues/11)
3. [x] [Task: Creating an invoice](https://github.com/mateuszdomagala/vue-invoice-app/issues/14)
4. [x] [Task: See all invoices on the homepage](https://github.com/mateuszdomagala/vue-invoice-app/issues/20)
5. [x] [Task: Filter by status](https://github.com/mateuszdomagala/vue-invoice-app/issues/19)
6. [x] [Task: Header - total number of invoices](https://github.com/mateuszdomagala/vue-invoice-app/issues/23)
7. [x] [Task: Route transitions](https://github.com/mateuszdomagala/vue-invoice-app/issues/31)
8. [x] [Task: Firestore rules and checking ownership](https://github.com/mateuszdomagala/vue-invoice-app/issues/33)
